### ISSUE TITLE
Got 7/6 on the second pokémon, not mentioned in the README. Bug?

### ISSUE THREAD

**Issue by EmrXald** [Leanny/SeedSearcher#9]
Hi.
After solving the CUDA isues I had yesterday(thanks a bunch for the help btw) I gave it another crack tonight and I ran into a new problem.

I caught my first 4th day pokémon(by advancing three days from my save point) and entered the stats. for the second slot this gave me a 7/6 which seemed odd but I kept going for the sake of it.
After having done my resets and caught the specificed(second 4th day pokemon) and reset for my 5th and 6th pokemon and hit search I got that no seed was found and the program asked me to increase IV deviation. to which the program promptly crashed as I tried to search again with a new IV deviation(also what should one change this number to, mine defaults to 0-10).

In anycase I will attach a txt of all the information on the pokémon I caught and maybe you can help me understand this 7/6 situation :) Den is 89, alternatively called Giant's Cap 4(rare version).

**Comment by Leanny** [comment]
Did you try the version that released 4h ago? These bugs should be fixed there

**Comment by EmrXald** [comment]
Of course I forgot to check for a new version! I will give it a try and get back to you :)
I'm not too savy with Git, where can I find a link to download the new version?

**Comment by EmrXald** [comment]
Update: Took the new version and am no longer getting the 7/6 bug, hurrah!

I Still failed to find a seed though and tried a few times by increasing my IV deviation in steps of 5. at the range 0-25 I got the following exception:

> ************** Exception Text **************
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at SeedSearcherGui.SeedSearcherGPU.MatrixStruct.CalculateInverseMatrix(Int32 length)
>    at SeedSearcherGui.SeedSearcherGPU.SearchSix(Device device, Int32 start, Int32 end, ToolStripStatusLabel updateLbl)
>    at SeedSearcherGui.SeedSearcher.CalculateGPU(Int32 searcherIDX, Int32 minRerolls, Int32 maxRerolls, Int32[] target, ToolStripStatusLabel updateLbl)
>    at SeedSearcherGui.SeedSearcherGui.<>c__DisplayClass34_0.<SearchImpl>b__0()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SeedSearcherGui.SeedSearcherGui.<SearchImpl>d__34.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

and before I forget again: the data I put into the program is in the attached txt file.
[2020-01-29.txt](https://github.com/Leanny/SeedSearcher/files/4130862/2020-01-29.txt)

**Comment by Leanny** [comment]
Thanks. I found out that 6/6 only supports deviation of up to 20. For 21 it crashes. I will figure out why and fix it for the next release.

If you are sure that everything is entered correctly then something else might be off. You can try to get the seed with your day 6 pkmn as day 4, as the ivs will result in 5/6, which should still be fast enough. So basically use das 6, 7, and 8 for this

Can you report back when you find the seed doing this and send me the seed? I will be able to identify the issue easier then :)

**Comment by EmrXald** [comment]
Hi.
Advanced two frames and did the process over again(so my day 6 pokémon was now my day 4) and it all worked out great this time!
[attempt 2.txt](https://github.com/Leanny/SeedSearcher/files/4133638/attempt.2.txt)

I got my seed in a minute or two and my shiny 250 advancements later! :D It all worked out great! ^^

attached a txt with the mons I used for the second try you recommened and my resulting seed.

**Comment by Leanny** [comment]
Thank you! I double checked your first document and your day 5 Pokémon was wrong. I calculated the IVs for each of your mons again.  Def IVs are 27 not 30.

I still need to fix the crash though... I will close the issue when it's fixed, for now please limit max deviation to 20
